//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieDBminiproj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watchlist
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public int UserID { get; set; }
        public string ImgPath { get; set; }
        public string Title { get; set; }
        public string ReleaseDate { get; set; }
        public int Runtime { get; set; }
    
        public virtual User User { get; set; }
    }
}
